# Site Information
title: Xin
description: "一个喜欢投资的工程师"
url: https://blog.twocatty.xin
repo: ahxinin/xin.github.io
lang: zh-CN
encoding: utf-8
timezone: Asia/Shanghai

# Social Media and External URLs
github: ahxinin
twitter: ahxinin
menu:
  - title: "About"
    url: "/about.html"
  - title: "Weekly"
    url: "https://weekly.twocatty.xin/"

# SEO and Analytics
google_analytics: G-Q3HX0EYJV5

# Build Settings
paginate: 10
post_ext: md
page_ext: md
post_layout: post
page_layout: page
titlecase: true
future: true
highlighter: rouge
markdown: kramdown
permalink: /:year-:month-:day/:title.html
sass:
  sass_dir: _sass
  style: compressed

collections:
  posts:
    output: true
    permalink: /:year-:month-:day/:title.html
  posts_en:
    output: true
    permalink: /en/:year-:month-:day/:title.html
    sort_by: date

include: [".htaccess"]
exclude:
  [
    "Gemfile",
    "Gemfile.lock",
    "README.md",
    "LICENSE",
    "package.json",
    "node_modules",
  ]

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-pdf-embed
  - jekyll-sitemap
  - jekyll-feed

# Custom Site Settings
showBuyCoffee: false
payImage: 
assetUrl: //blog.twocatty.xin/images/
defaultImage: data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==

